### ISSUE TITLE
easage-list.cmd

### ISSUE THREAD

**Issue by triatomic** [Phrohdoh/easage#28]
Hello, can you let this command to print out a log file ?

**Comment by phrohdoh** [comment]
Hi @triatomic!

Could you be more specific, please?

What would you like to see that you are not seeing already?

Below is the help content for the `list` command (which `easage-list.cmd` authored by @Teteros wraps):

```
easage-list 
Taryn Hill <taryn@phrohdoh.com>
List the contents of a BIG archive

USAGE:
    easage list [FLAGS] <source>

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information
        --verbose    if supplied output more information (typically only useful for developing easage itself)

ARGS:
    <source>    path to the BIG to read
```

If you would like to see more information than just the contained filepaths you can:

1) Invoke `easage list yourfile.big --verbose` directly, or
2) Change `set verbose=` to `set verbose=1` in `easage-list.cmd`

Please let me know if this helps and thanks for using `easaage`!

**Comment by Teteros** [comment]
@triatomic I've had this functionality in the first version of the script (it was also looping through each file in selection, like easage-pack.cmd, or easage-unpack.cmd) but I've ended up having too much nested `if` statements which batch files/cmd.exe don't like very much.

You can change [this](https://github.com/Phrohdoh/easage/blob/master/contrib/easage-list.cmd#L25) line to output to a fixed file.

e.g:
```cmd
set out=easage-list.log
if defined verbose (easage list --verbose "%~nx1" >"%out%") else (easage list "%~nx1" >"%out%")
```
