### ISSUE TITLE
Option to set which BIG format to use for packing

### ISSUE THREAD

**Issue by Teteros** [Phrohdoh/easage#9]
Currently you can only change BIG format to use for packing only at compile time.
https://github.com/Phrohdoh/easage/blob/master/src/bin/easage_pack.rs#L35

A runtime `easage pack` option to pick the BIG kind to pack into would be more user friendly.

**Comment by phrohdoh** [comment]
I agree entirely. Would you be interested in taking this on?

**Comment by Teteros** [comment]
It sounds simple enough, I'll look into it after #10 is resolved.

**Comment by Teteros** [comment]
https://github.com/Phrohdoh/easage/commit/16997aba06e2e004de3ded758e4542d670821b3f closes this, thanks.

**Comment by phrohdoh** [comment]
16997aba06e2e004de3ded758e4542d670821b3f added a `kind` flag to the `easage pack` command.

```
--kind <kind>        BIG archive kind (BIGF or BIG4, case-sensitive)
```

Example usage:
```
$ easage pack --source WindowSource/ --output window-easage-new.big --kind BIGF 
```

An incorrect value will yield an error such as:
```
$ easage pack --source WindowSource/ --output window-easage-new.big --kind BIG5
error: Invalid value for '--kind <kind>': kind must be one of 'BIGF' or 'BIG4'
```
